sudo: required
dist: trusty

os:
- osx
- linux

addons:
  apt:
    packages:
    - build-essential
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev

language: node_js
node_js:
- '6'

before_install:
  - ./scripts/travis-xvfb.sh
  - rm -rf node_modules
  - npm cache clean --force
  - npm install -g gulp
  - npm install

cache:
  directories:
  - node_modules
  - app/node_modules

script:
  # - npm run travis
- ./node_modules/.bin/fission-ping

notifications:
  webhooks:
    urls:
      - https://zulip.org/zulipbot/travis
    on_success: always
    on_failure: always
